language: java
git:
  depth: 1
jdk:
  - openjdk8
dist: trusty
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  username: grini.hraf@dauphine.fr
  password: $BLUEMIX_PASSWORD
  organization: grini.hraf@dauphine.fr
  space: dev
region: eu-gb
